# Generated by Django 4.2.7 on 2023-11-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.IntegerField(default=0),
        ),
    ]
