# Generated by Django 4.2.7 on 2023-11-23 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_user_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='post',
            new_name='post_count',
        ),
    ]
