# Generated by Django 4.2.8 on 2023-12-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_post_comment_count_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmark_count',
            field=models.IntegerField(default=0),
        ),
    ]
