# Generated by Django 4.2.8 on 2023-12-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0009_user_bookmark_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmark',
            field=models.IntegerField(default=0),
        ),
    ]
