# Generated by Django 4.2.8 on 2023-12-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0010_post_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=255)),
                ('descritpion', models.CharField(blank=True, max_length=255)),
                ('craeted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='list',
            field=models.ManyToManyField(to='twitter.lists'),
        ),
    ]
