# Generated by Django 4.2.8 on 2023-12-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0012_lists_user_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='list',
            field=models.ManyToManyField(blank=True, to='twitter.lists'),
        ),
    ]
